kind: pipeline
name: default

steps:
  - name: app-test
    image: bluerain/zheckin:build
    pull: true
    environment:
      ZHECKIN_ENV: test
      ZHECKIN_ZHIHU_API_TOKEN:
        from_secret: zhihu_api_token
      ZHECKIN_BASE_SECRET_KEY: test123
    commands:
      - shards --production
      - mkdir data
      - crystal sam.cr -- db:setup
      - crystal spec

  - name: assets-build
    image: node:stretch
    commands:
      - npm install --prefix ./assets
      - npm run deploy --prefix ./assets

  - name: app-build
    image: bluerain/zheckin:build
    pull: true
    commands:
      - shards build zheckin --release --progress --production
      - crystal sam.cr -- digests:make
      - crystal sam.cr -- digests:clean_undigested

  - name: app-image-push
    image: plugins/docker
    settings:
      repo: bluerain/zheckin
      username: bluerain
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      tags: latest
    when:
      branch:
        - master
      event:
        - push

  - name: sam-build
    image: bluerain/zheckin:build
    pull: true
    commands:
      - shards build sam --release --progress --production
    when:
      branch:
        - sam/update
      event:
        - push

  - name: sam-image-push
    image: plugins/docker
    settings:
      repo: bluerain/zheckin
      username: bluerain
      password:
        from_secret: docker_password
      dockerfile: sam.Dockerfile
      tags: sam
    when:
      branch:
        - sam/update
      event:
        - push
