version: "3"

services:
  server:
    image: bluerain/zheckin
    stdin_open: true
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Shanghai
      ZHECKIN_ZHIHU_API_TOKEN: "${ZHECKIN_ZHIHU_API_TOKEN}"
      ZHECKIN_BASE_SECRET_KEY: "${ZHECKIN_BASE_SECRET_KEY}"
      ZHECKIN_SCHEDULE_HOUR: "${ZHECKIN_SCHEDULE_HOUR}"
      ZHECKIN_SCHEDULE_MINUTE: "${ZHECKIN_SCHEDULE_MINUTE}"
    restart: always
